
-- Get Original Transmission
USE SCHEMA DATA;
USE WAREHOUSE WH_RESEARCH;
USE DATABASE CPE_DEV;



UPDATE CPE_DEV.DATA.CLAIMS_COMPLETE AS TARGET
SET
  TARGET.REVERSED = TRUE,
  TARGET.REVERSAL_TIME = CHANGES.MAX_TIME_PROCESSED,
  TARGET.REVERSED_RECORD_ID = CHANGES.RECORD_ID
FROM
(
    -- NOTE: This collects those reversal requests of status 'D', 'Q', 'S' that should be considered for reversal.
    SELECT SERVICE_PROVIDER_NPI, DATE_OF_SERVICE, RX_NUMBER, FILL_NUMBER, RECORD_ID, MAX(DATE_TIME_TRANSACTION_PROCESSED) AS MAX_TIME_PROCESSED, CURRENT_TIMESTAMP() AS PROCESS_TIME
    FROM CPE_DEV.DATA.CPE_CLAIM_REVERSAL_REQUESTS
    WHERE (BIN != '747474' AND RESPONSE_STATUS_CODE IN ('D', 'Q', 'S')) -- Allow CASH transactions with no RESPONSE_STATUS_CODE
    GROUP BY SERVICE_PROVIDER_NPI, DATE_OF_SERVICE, RX_NUMBER, FILL_NUMBER, RECORD_ID
) CHANGES
WHERE TARGET.DATE_TIME_TRANSACTION_PROCESSED >= CURRENT_DATE - INTERVAL '5 YEAR' -- Added time filter
    AND TARGET.DATE_TIME_TRANSACTION_PROCESSED < CHANGES.MAX_TIME_PROCESSED
    AND TARGET.RX_NUMBER = CHANGES.RX_NUMBER
    AND TARGET.FILL_NUMBER = CHANGES.FILL_NUMBER
    AND TARGET.DATE_OF_SERVICE = CHANGES.DATE_OF_SERVICE
    AND TARGET.SERVICE_PROVIDER_NPI = CHANGES.SERVICE_PROVIDER_NPI
    -- Updated logic to handle BIN 747474 without RESPONSE_STATUS_CODE
    AND (TARGET.BIN = '747474' OR TARGET.RESPONSE_STATUS_CODE IN ('P', 'C', 'A'))
    AND TARGET.REVERSED = FALSE
;


SELECT COUNT(*)
FROM CPE_DEV.DATA.CLAIMS_COMPLETE as TARGET
JOIN (
    -- NOTE: This collects those reversal requests of status 'D', 'Q', 'S' that should be considered for reversal.
    SELECT SERVICE_PROVIDER_NPI, DATE_OF_SERVICE, RX_NUMBER, FILL_NUMBER, RECORD_ID, MAX(DATE_TIME_TRANSACTION_PROCESSED) AS MAX_TIME_PROCESSED, CURRENT_TIMESTAMP() AS PROCESS_TIME
    FROM CPE_DEV.DATA.CPE_CLAIM_REVERSAL_REQUESTS
    WHERE (BIN != '747474' AND RESPONSE_STATUS_CODE IN ('D', 'Q', 'S')) -- Allow CASH transactions with no RESPONSE_STATUS_CODE
    GROUP BY SERVICE_PROVIDER_NPI, DATE_OF_SERVICE, RX_NUMBER, FILL_NUMBER, RECORD_ID
) AS CHANGES
  ON TARGET.DATE_TIME_TRANSACTION_PROCESSED >= CURRENT_DATE - INTERVAL '5 YEAR' -- Added time filter
    AND TARGET.DATE_TIME_TRANSACTION_PROCESSED < CHANGES.MAX_TIME_PROCESSED
    AND TARGET.RX_NUMBER = CHANGES.RX_NUMBER
    AND TARGET.FILL_NUMBER = CHANGES.FILL_NUMBER
    AND TARGET.DATE_OF_SERVICE = CHANGES.DATE_OF_SERVICE
    AND TARGET.SERVICE_PROVIDER_NPI = CHANGES.SERVICE_PROVIDER_NPI
    -- Updated logic to handle BIN 747474 without RESPONSE_STATUS_CODE
    AND (TARGET.BIN = '747474' OR TARGET.RESPONSE_STATUS_CODE IN ('P', 'C', 'A'))
    AND TARGET.REVERSED = FALSE
;