// Clinical+ Import  tables have changed in the last hour?
SELECT 'patient' as tbl, COUNT(*) as cnt FROM CPE_PROD.DATA.CLINICALPLUS_PATIENT
UNION ALL
SELECT 'patient (HOUR AGO)' as tbl, COUNT(*) as cnt FROM CPE_PROD.DATA.CLINICALPLUS_PATIENT AT(OFFSET => -3600)
UNION ALL
SELECT 'patientrx' as tbl, COUNT(*) as cnt FROM CPE_PROD.DATA.CLINICALPLUS_PATIENT_RX
UNION ALL
SELECT 'patientrx (HOUR AGO)' as tbl, COUNT(*) as cnt FROM CPE_PROD.DATA.CLINICALPLUS_PATIENT_RX AT(OFFSET => -3600)
UNION ALL
SELECT 'campaign_alert_history' as tbl, COUNT(*) as cnt FROM CPE_PROD.DATA.CLINICALPLUS_CAMPAIGN_ALERT_HISTORY
UNION ALL
SELECT 'campaign_alert_history (HOUR AGO)' as tbl, COUNT(*) as cnt FROM CPE_PROD.DATA.CLINICALPLUS_CAMPAIGN_ALERT_HISTORY AT(OFFSET => -3600)
;
