SELECT 'CAMPAIGN' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN
UNION ALL
SELECT 'CAMPAIGN_CRITERIA', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_CRITERIA
UNION ALL
SELECT 'CAMPAIGN_CRITERIA_TYPE', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_CRITERIA_TYPE
UNION ALL
SELECT 'CAMPAIGN_NOTIFICATION_TEXT', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_TEXT
UNION ALL
SELECT 'CAMPAIGN_NOTIFICATION_VERSION', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_VERSION
UNION ALL
SELECT 'CAMPAIGN_PATIENT', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PATIENT
UNION ALL
SELECT 'CAMPAIGN_PATIENT_NOTIFICATION', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PATIENT_NOTIFICATION
UNION ALL
SELECT 'CAMPAIGN_PHARMACY_NOTIFICATION', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PHARMACY_NOTIFICATION
UNION ALL
SELECT 'CAMPAIGN_STATUS', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_STATUS
UNION ALL
SELECT 'CAMPAIGN_TYPE', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_TYPE
UNION ALL
SELECT 'CAMPAIGN_WORKFLOW', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_WORKFLOW
UNION ALL
SELECT 'IMAGE', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.IMAGE
UNION ALL
SELECT 'LABEL_TYPE', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.LABEL_TYPE
UNION ALL
SELECT 'LANGUAGE_TYPE', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.LANGUAGE_TYPE
UNION ALL
SELECT 'LOCATION', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.LOCATION
UNION ALL
SELECT 'LOCATION_FILTER_TYPE', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.LOCATION_FILTER_TYPE
UNION ALL
SELECT 'LOCATION_OPT_IN_CAMPAIGN', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.LOCATION_OPT_IN_CAMPAIGN
UNION ALL
SELECT 'LOCATION_OPT_OUT_CAMPAIGN', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.LOCATION_OPT_OUT_CAMPAIGN
UNION ALL
SELECT 'NOTIFICATION_RESPONSE', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.NOTIFICATION_RESPONSE
UNION ALL
SELECT 'NOTIFICATION_TYPE', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.NOTIFICATION_TYPE
UNION ALL
SELECT 'OPT_STATUS', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.OPT_STATUS
UNION ALL
SELECT 'PATIENT_OPT_OUT_CAMPAIGN', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.PATIENT_OPT_OUT_CAMPAIGN
UNION ALL
SELECT 'PATIENT_RX_OPT_OUT_CAMPAIGN', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.PATIENT_RX_OPT_OUT_CAMPAIGN
UNION ALL
SELECT 'PATIENT_RX_PAYMENT_INFO', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.PATIENT_RX_PAYMENT_INFO
UNION ALL
SELECT 'PATIENT_RX_PRESCRIBER_INFO', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.PATIENT_RX_PRESCRIBER_INFO
UNION ALL
SELECT 'RX_VOUCHER', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.RX_VOUCHER
UNION ALL
SELECT 'SUCCESSFUL_ALERT_TYPE', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.SUCCESSFUL_ALERT_TYPE
UNION ALL
SELECT 'TABLE_LOG', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.TABLE_LOG
UNION ALL
SELECT 'THIRD_PARTY_TYPE', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.THIRD_PARTY_TYPE
UNION ALL
SELECT 'VENDOR_API_SETTING', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.VENDOR_API_SETTING
UNION ALL
SELECT 'VENDOR_PATIENT', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.VENDOR_PATIENT
UNION ALL
SELECT 'VENDOR_TYPE', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.VENDOR_TYPE
UNION ALL
SELECT 'VOUCHER_STATUS', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.VOUCHER_STATUS
UNION ALL
SELECT 'WORKFLOW_TYPE', COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.WORKFLOW_TYPE
UNION ALL
SELECT 'CAMPAIGN_ALERT_HISTORY', COUNT(*) FROM CPE_PROD.DATA.CLINICALPLUS_CAMPAIGN_ALERT_HISTORY
UNION ALL
SELECT 'PATIENT', COUNT(*) FROM CPE_PROD.DATA.CLINICALPLUS_PATIENT
UNION ALL
SELECT 'PATIENT_RX', COUNT(*) FROM CPE_PROD.DATA.CLINICALPLUS_PATIENT_RX

ORDER BY object_name ASC
;