----------------------------------------------------------------------------------------------------
--DEV-
----------------------------------------------------------------------------------------------------

-- VOUCHER STATUS
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.VOUCHER_STATUS;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_VOUCHER_STATUS;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_VOUCHER_STATUS;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.VOUCHER_STATUS limit 100;

-- VENDOR API SETTING
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.VENDOR_API_SETTING;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_VENDOR_API_SETTING;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_VENDOR_API_SETTING;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.VENDOR_API_SETTING limit 100;

-- CAMPAIGN
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_CAMPAIGN;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN limit 100;

-- CAMPAIGN CRITERIA
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_CAMPAIGN_CRITERIA;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_CRITERIA;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_CRITERIA;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_CRITERIA limit 100;

-- CAMPAIGN_CRITERIA_TYPE
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_CAMPAIGN_CRITERIA_TYPE;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_CRITERIA_TYPE;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_CRITERIA_TYPE;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_CRITERIA_TYPE limit 100;

-- CAMPAIGN_NOTIFICATION_TEXT
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_CAMPAIGN_NOTIFICATION_TEXT;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_NOTIFICATION_TEXT;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_TEXT;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_TEXT limit 100;

-- CAMPAIGN_NOTIFICATION_VERSION
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_CAMPAIGN_NOTIFICATION_VERSION;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_NOTIFICATION_VERSION;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_VERSION;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_VERSION limit 100;

-- CAMPAIGN_PATIENT_NOTIFICATION
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_CAMPAIGN_PATIENT_NOTIFICATION;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_PATIENT_NOTIFICATION;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_PATIENT_NOTIFICATION;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_PATIENT_NOTIFICATION limit 100;

-- CAMPAIGN_PHARMACY_NOTIFICATION
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_CAMPAIGN_PHARMACY_NOTIFICATION;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_PHARMACY_NOTIFICATION;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_PHARMACY_NOTIFICATION;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_PHARMACY_NOTIFICATION limit 100;

-- CAMPAIGN_STATUS
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_CAMPAIGN_STATUS;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_STATUS;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_STATUS;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_STATUS limit 100;

-- CAMPAIGN_WORKFLOW
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_CAMPAIGN_WORKFLOW;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_WORKFLOW;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_WORKFLOW;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_WORKFLOW limit 100;

-- IMAGE
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_IMAGE;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_IMAGE;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.IMAGE;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.IMAGE limit 100;

-- LABEL_TYPE
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_LABEL_TYPE;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_LABEL_TYPE;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.LABEL_TYPE;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.LABEL_TYPE limit 100;

-- LANGUAGE_TYPE
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_LANGUAGE_TYPE;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_LANGUAGE_TYPE;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.LANGUAGE_TYPE;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.LANGUAGE_TYPE limit 100;

-- LOCATION
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_LOCATION;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_LOCATION;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.LOCATION;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.LOCATION limit 100;

-- LOCATION_OPT_IN_CAMPAIGN
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_LOCATION_OPT_IN_CAMPAIGN;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_LOCATION_OPT_IN_CAMPAIGN;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.LOCATION_OPT_IN_CAMPAIGN;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.LOCATION_OPT_IN_CAMPAIGN limit 100;

-- LOCATION_FILTER_TYPE
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_LOCATION_FILTER_TYPE;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_LOCATION_FILTER_TYPE;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.LOCATION_FILTER_TYPE;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.LOCATION_FILTER_TYPE limit 100;

-- LOCATION_OPT_OUT_CAMPAIGN
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_LOCATION_OPT_OUT_CAMPAIGN;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_LOCATION_OPT_OUT_CAMPAIGN;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.LOCATION_OPT_OUT_CAMPAIGN;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.LOCATION_OPT_OUT_CAMPAIGN limit 100;

-- NOTIFICATION_RESPONSE
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_NOTIFICATION_RESPONSE;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_NOTIFICATION_RESPONSE;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.NOTIFICATION_RESPONSE;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.NOTIFICATION_RESPONSE limit 100;

-- NOTIFICATION_TYPE
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_NOTIFICATION_TYPE;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_NOTIFICATION_TYPE;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.NOTIFICATION_TYPE;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.NOTIFICATION_TYPE limit 100;

-- OPT_STATUS
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_OPT_STATUS;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_OPT_STATUS;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.OPT_STATUS;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.OPT_STATUS limit 100;

-- PATIENT_OPT_OUT_CAMPAIGN
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_PATIENT_OPT_OUT_CAMPAIGN;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_PATIENT_OPT_OUT_CAMPAIGN;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.PATIENT_OPT_OUT_CAMPAIGN;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.PATIENT_OPT_OUT_CAMPAIGN limit 100;

-- PATIENT_RX_OPT_OUT_CAMPAIGN
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_PATIENT_RX_OPT_OUT_CAMPAIGN;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_PATIENT_RX_OPT_OUT_CAMPAIGN;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.PATIENT_RX_OPT_OUT_CAMPAIGN;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.PATIENT_RX_OPT_OUT_CAMPAIGN limit 100;

-- PATIENT_RX_PAYMENT_INFO
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_PATIENT_RX_PAYMENT_INFO;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_PATIENT_RX_PAYMENT_INFO;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.PATIENT_RX_PAYMENT_INFO;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.PATIENT_RX_PAYMENT_INFO limit 100;

-- PATIENT_RX_PRESCRIBER_INFO
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_PATIENT_RX_PRESCRIBER_INFO;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_PATIENT_RX_PRESCRIBER_INFO;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.PATIENT_RX_PRESCRIBER_INFO;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.PATIENT_RX_PRESCRIBER_INFO limit 100;

-- RX_VOUCHER
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_RX_VOUCHER;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_RX_VOUCHER;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.RX_VOUCHER;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.RX_VOUCHER limit 100;

-- SUCCESSFUL_ALERT_TYPE
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_SUCCESSFUL_ALERT_TYPE;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_SUCCESSFUL_ALERT_TYPE;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.SUCCESSFUL_ALERT_TYPE;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.SUCCESSFUL_ALERT_TYPE limit 100;
--====================================================================================================
-- TEST LINE (DEV)
--====================================================================================================

-- Snowflake (DEV)
SELECT 'WORKFLOW_TYPE' AS table_name, COUNT(*) AS row_count FROM CPE_DEV.CLINICAL_PLUS.WORKFLOW_TYPE
UNION ALL
SELECT 'VOUCHER_STATUS', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.VOUCHER_STATUS
UNION ALL
SELECT 'VENDOR_TYPE', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.VENDOR_TYPE
UNION ALL
SELECT 'VENDOR_PATIENT', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.VENDOR_PATIENT
UNION ALL
SELECT 'VENDOR_API_SETTING', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.VENDOR_API_SETTING
UNION ALL
SELECT 'THIRD_PARTY_TYPE', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.THIRD_PARTY_TYPE
UNION ALL
SELECT 'TABLE_LOG', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.TABLE_LOG
UNION ALL
SELECT 'SUCCESSFUL_ALERT_TYPE', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.SUCCESSFUL_ALERT_TYPE
UNION ALL
SELECT 'RX_VOUCHER', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.RX_VOUCHER
UNION ALL
SELECT 'PATIENT_RX_PRESCRIBER_INFO', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.PATIENT_RX_PRESCRIBER_INFO
UNION ALL
SELECT 'PATIENT_RX_PAYMENT_INFO', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.PATIENT_RX_PAYMENT_INFO
UNION ALL
SELECT 'PATIENT_RX_OPT_OUT_CAMPAIGN', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.PATIENT_RX_OPT_OUT_CAMPAIGN
UNION ALL
SELECT 'PATIENT_OPT_OUT_CAMPAIGN', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.PATIENT_OPT_OUT_CAMPAIGN
UNION ALL
SELECT 'OPT_STATUS', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.OPT_STATUS
UNION ALL
SELECT 'NOTIFICATION_TYPE', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.NOTIFICATION_TYPE
UNION ALL
SELECT 'NOTIFICATION_RESPONSE', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.NOTIFICATION_RESPONSE
UNION ALL
SELECT 'LOCATION_OPT_OUT_CAMPAIGN', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.LOCATION_OPT_OUT_CAMPAIGN
UNION ALL
SELECT 'LOCATION_OPT_IN_CAMPAIGN', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.LOCATION_OPT_IN_CAMPAIGN
UNION ALL
SELECT 'LOCATION_FILTER_TYPE', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.LOCATION_FILTER_TYPE
UNION ALL
SELECT 'LOCATION', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.LOCATION
UNION ALL
SELECT 'LANGUAGE_TYPE', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.LANGUAGE_TYPE
UNION ALL
SELECT 'LABEL_TYPE', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.LABEL_TYPE
UNION ALL
SELECT 'IMAGE', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.IMAGE
UNION ALL
SELECT 'CAMPAIGN_WORKFLOW', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_WORKFLOW
UNION ALL
SELECT 'CAMPAIGN_STATUS', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_STATUS
UNION ALL
SELECT 'CAMPAIGN_PHARMACY_NOTIFICATION', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_PHARMACY_NOTIFICATION
UNION ALL
SELECT 'CAMPAIGN_PATIENT_NOTIFICATION', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_PATIENT_NOTIFICATION
UNION ALL
SELECT 'CAMPAIGN_PATIENT', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_PATIENT
UNION ALL
SELECT 'CAMPAIGN_NOTIFICATION_VERSION', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_VERSION
UNION ALL
SELECT 'CAMPAIGN_NOTIFICATION_TEXT', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_TEXT
UNION ALL
SELECT 'CAMPAIGN_CRITERIA_TYPE', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_CRITERIA_TYPE
UNION ALL
SELECT 'CAMPAIGN_CRITERIA', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_CRITERIA
UNION ALL
SELECT 'CAMPAIGN', COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN

ORDER BY table_name DESC
;

-- TABLE_LOG
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_TABLE_LOG;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_TABLE_LOG;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.TABLE_LOG;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.TABLE_LOG limit 100;

-- THIRD_PARTY_TYPE
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_THIRD_PARTY_TYPE;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_THIRD_PARTY_TYPE;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.THIRD_PARTY_TYPE;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.THIRD_PARTY_TYPE limit 100;

-- VENDOR_PATIENT
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_VENDOR_PATIENT;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_VENDOR_PATIENT;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.VENDOR_PATIENT;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.VENDOR_PATIENT limit 100;

-- VENDOR_TYPE
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_VENDOR_TYPE;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_VENDOR_TYPE;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.VENDOR_TYPE;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.VENDOR_TYPE limit 100;

-- WORKFLOW_TYPE
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_WORKFLOW_TYPE;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_WORKFLOW_TYPE;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.WORKFLOW_TYPE;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.WORKFLOW_TYPE limit 100;

-- CAMPAIGN_PATIENT
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.STREAM_CAMPAIGN_PATIENT;
EXECUTE TASK CPE_DEV.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_PATIENT;
SELECT COUNT(*) FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_PATIENT;
SELECT * FROM CPE_DEV.CLINICAL_PLUS.CAMPAIGN_PATIENT limit 100;

----------------------------------------------------------------------------------------------------
--PROD--
----------------------------------------------------------------------------------------------------

-- VOUCHER STATUS
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.VOUCHER_STATUS;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VOUCHER_STATUS;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_VOUCHER_STATUS;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.VOUCHER_STATUS limit 100;

-- VENDOR API SETTING
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.VENDOR_API_SETTING;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VENDOR_API_SETTING;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_VENDOR_API_SETTING;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.VENDOR_API_SETTING limit 100;

-- CAMPAIGN
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN limit 100;

-- CAMPAIGN CRITERIA
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_CRITERIA;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_CRITERIA;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_CRITERIA;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_CRITERIA limit 100;

-- CAMPAIGN_CRITERIA_TYPE
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_CRITERIA_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_CRITERIA_TYPE;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_CRITERIA_TYPE;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_CRITERIA_TYPE limit 100;

-- CAMPAIGN_NOTIFICATION_TEXT
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_NOTIFICATION_TEXT;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_NOTIFICATION_TEXT;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_TEXT;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_TEXT limit 100;

-- CAMPAIGN_NOTIFICATION_VERSION
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_NOTIFICATION_VERSION;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_NOTIFICATION_VERSION;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_VERSION;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_VERSION limit 100;

-- CAMPAIGN_PATIENT_NOTIFICATION
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_PATIENT_NOTIFICATION;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_PATIENT_NOTIFICATION;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PATIENT_NOTIFICATION;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PATIENT_NOTIFICATION limit 100;

-- CAMPAIGN_PHARMACY_NOTIFICATION
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_PHARMACY_NOTIFICATION;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_PHARMACY_NOTIFICATION;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PHARMACY_NOTIFICATION;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PHARMACY_NOTIFICATION limit 100;

-- CAMPAIGN_STATUS
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_STATUS;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_STATUS;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_STATUS;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_STATUS limit 100;

-- CAMPAIGN_WORKFLOW
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_WORKFLOW;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_WORKFLOW;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_WORKFLOW;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_WORKFLOW limit 100;

-- IMAGE
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_IMAGE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_IMAGE;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.IMAGE;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.IMAGE limit 100;

-- LABEL_TYPE
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_LABEL_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LABEL_TYPE;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.LABEL_TYPE;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.LABEL_TYPE limit 100;

-- LANGUAGE_TYPE
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_LANGUAGE_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LANGUAGE_TYPE;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.LANGUAGE_TYPE;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.LANGUAGE_TYPE limit 100;

-- LOCATION
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_LOCATION;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.LOCATION;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.LOCATION limit 100;

-- LOCATION_FILTER_TYPE
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_LOCATION_FILTER_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_FILTER_TYPE;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.LOCATION_FILTER_TYPE;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.LOCATION_FILTER_TYPE limit 100;

-- LOCATION_OPT_IN_CAMPAIGN
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_LOCATION_OPT_IN_CAMPAIGN;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_OPT_IN_CAMPAIGN;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.LOCATION_OPT_IN_CAMPAIGN;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.LOCATION_OPT_IN_CAMPAIGN limit 100;

-- LOCATION_OPT_OUT_CAMPAIGN
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_LOCATION_OPT_OUT_CAMPAIGN;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_OPT_OUT_CAMPAIGN;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.LOCATION_OPT_OUT_CAMPAIGN;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.LOCATION_OPT_OUT_CAMPAIGN limit 100;

-- NOTIFICATION_RESPONSE
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_NOTIFICATION_RESPONSE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_NOTIFICATION_RESPONSE;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.NOTIFICATION_RESPONSE;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.NOTIFICATION_RESPONSE limit 100;

-- NOTIFICATION_TYPE
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_NOTIFICATION_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_NOTIFICATION_TYPE;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.NOTIFICATION_TYPE;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.NOTIFICATION_TYPE limit 100;

-- OPT_STATUS
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_OPT_STATUS;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_OPT_STATUS;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.OPT_STATUS;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.OPT_STATUS limit 100;

-- PATIENT_RX_OPT_OUT_CAMPAIGN
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_PATIENT_RX_OPT_OUT_CAMPAIGN;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_PATIENT_RX_OPT_OUT_CAMPAIGN;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.PATIENT_RX_OPT_OUT_CAMPAIGN;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.PATIENT_RX_OPT_OUT_CAMPAIGN limit 100;

-- PATIENT_RX_PAYMENT_INFO
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_PATIENT_RX_PRESCRIBER_INFO;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_PATIENT_RX_PRESCRIBER_INFO;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.PATIENT_RX_PRESCRIBER_INFO;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.PATIENT_RX_PRESCRIBER_INFO limit 100;

-- TABLE_LOG
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_TABLE_LOG;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_TABLE_LOG;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.TABLE_LOG;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.TABLE_LOG limit 100;

-- THIRD_PARTY_TYPE
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_THIRD_PARTY_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_THIRD_PARTY_TYPE;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.THIRD_PARTY_TYPE;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.THIRD_PARTY_TYPE limit 100;

-- VENDOR_PATIENT
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_VENDOR_PATIENT;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VENDOR_PATIENT;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.VENDOR_PATIENT;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.VENDOR_PATIENT limit 100;

-- VENDOR_TYPE
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_VENDOR_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VENDOR_TYPE;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.VENDOR_TYPE;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.VENDOR_TYPE limit 100;

-- WORKFLOW_TYPE
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_WORKFLOW_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_WORKFLOW_TYPE;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.WORKFLOW_TYPE;
SELECT * FROM CPE_PROD.CLINICAL_PLUS.WORKFLOW_TYPE limit 100;
