USE DATABASE CPE_PROD;
USE SCHEMA DATA;

SELECT * FROM CPE_PROD.DATA.STREAM_RULE_DATA_PLAN;
SELECT * FROM CPE_PROD.DATA.STREAM_RULE_DATA_PLAN_PCN;

SHOW GRANTS TO ROLE DATA_COLLECTIONS;
SHOW GRANTS TO ROLE DATA_COLLECTIONS_DEV;
