SELECT * FROM db_exported_control;

-- Description: Queries to monitor and resync Pharmacy Switch Service data in Snowflake
SELECT CURRENT_TIMESTAMP();

-- Show EVENT Imports
SELECT *
FROM snowflake.account_usage.copy_history
WHERE LAST_LOAD_TIME >  '2025-12-04 12:00:00.000000000 -08:00'
AND pipe_name = 'EVENTS'
AND TABLE_CATALOG_NAME = 'CPE_PROD'
AND ROW_COUNT > 0
AND FILE_NAME LIKE ANY ('%PharmacySwitchServiceTableRecord%', '%SwitchServiceTableRecord%')
ORDER BY last_load_time DESC
LIMIT 1000;


SELECT *
FROM snowflake.account_usage.copy_history
WHERE LAST_LOAD_TIME >  '2025-12-03 11:32:13.700000000 -08:00'
AND pipe_name = 'EVENTS'
AND TABLE_CATALOG_NAME = 'CPE_DEV'
AND ROW_COUNT > 0
AND FILE_NAME LIKE ANY ('%PharmacySwitchServiceTableRecord%', '%SwitchServiceTableRecord%')
ORDER BY last_load_time DESC
LIMIT 1000;


// Table Count
SELECT COUNT(*) FROM CPE_PROD.DATA_DICTIONARY.RULEDATA_PHARMACY_SWITCH_SERVICE;
SELECT COUNT(*) FROM CPE_PROD.DATA.SWITCH_SERVICE_TEST_AND_DELETE;
SELECT COUNT(*) FROM CPE_PROD.DATA.SWITCH_SERVICE;
SELECT COUNT(*) FROM CPE_PROD.DATA.PHARMACY_SWITCH_SERVICE;

//Stream Count
SELECT COUNT(*) FROM CPE_PROD.DATA_DICTIONARY.STREAM_RULEDATA_PHARMACY_SWITCH_SERVICE;
SELECT COUNT(*) FROM CPE_PROD.DATA.STREAM_SWITCH_SERVICE_TEST_AND_DELETE;
SELECT COUNT(*) FROM CPE_PROD.DATA.STREAM_PHARMACY_SWITCH_SERVICE;
SELECT * FROM CPE_PROD.DATA.STREAM_SWITCH_SERVICE;

DESCRIBE TASK CPE_PROD.DATA.STREAM_TASK_PHARMACY_SWITCH_SERVICE;
//====================================================================================================
// [SNOWFLAKE] DEV - Resync Steps
//====================================================================================================

SELECT COUNT(*) FROM CPE_PROD.STAGING.STAGE_EVENTS WHERE DATA:eventType::VARCHAR IN (
     'SwitchDataExport-PharmacySwitchServiceTableRecord'
--      'SwitchDataExport-SwitchServiceTableRecord'
);

SELECT
        DATA:eventType::VARCHAR as eventType,
        COUNT(*) as cnt
        FROM CPE_PROD.STAGING.STAGE_EVENTS
        WHERE DATA:operationType::VARCHAR <> ''
        AND INGESTED_TIMESTAMP > '2025-12-02 00:00:00.000'
        GROUP BY DATA:eventType::VARCHAR;

--          WHERE DATA:eventType::VARCHAR IN ( 'SwitchDataExport-PharmacySwitchServiceTableRecord', 'SwitchDataExport-SwitchServiceTableRecord' )
--            AND   DATA:operationType::VARCHAR  = 'DELETE';

SELECT COUNT(*) FROM CPE_PROD.STAGING.STAGE_EVENTS WHERE DATA:eventType::VARCHAR IN ( 'SwitchDataExport-PharmacySwitchServiceTableRecord', 'SwitchDataExport-SwitchServiceTableRecord' );

SELECT
    DATA:eventType::VARCHAR as eventType,
    DATA:eventPayload.id::VARCHAR as recordId,
    *
FROM CPE_PROD.STAGING.STAGE_EVENTS
WHERE DATA:eventType::VARCHAR IN (
    'SwitchDataExport-PharmacySwitchServiceTableRecord'
--     'SwitchDataExport-SwitchServiceTableRecord'
)
AND DATA:eventPayload.id::VARCHAR = '1318649243049299968'
ORDER BY INGESTED_TIMESTAMP DESC
;

// Delete Raw Events
-- DELETE FROM CPE_PROD.STAGING.STAGE_EVENTS WHERE DATA:eventType::VARCHAR IN ( 'SwitchDataExport-PharmacySwitchServiceTableRecord', 'SwitchDataExport-SwitchServiceTableRecord' );

// Drop Previous Backup Tables
-- DROP TABLE IF EXISTS CPE_DEV.DATA_DICTIONARY.RULEDATA_PHARMACY_SWITCH_SERVICE_BAK;
-- DROP TABLE IF EXISTS CPE_DEV.DATA.SWITCH_SERVICE_TEST_AND_DELETE_BAK;
-- DROP TABLE IF EXISTS CPE_DEV.DATA.PHARMACY_SWITCH_SERVICE_BAK;
-- DROP TABLE IF EXISTS CPE_DEV.DATA.SWITCH_SERVICE_BAK;

// Clone Tables As Back
-- CREATE TABLE CPE_PROD.DATA_DICTIONARY.RULEDATA_PHARMACY_SWITCH_SERVICE_BAK CLONE CPE_PROD.DATA_DICTIONARY.RULEDATA_PHARMACY_SWITCH_SERVICE;
-- CREATE TABLE CPE_PROD.DATA.SWITCH_SERVICE_TEST_AND_DELETE_BAK CLONE CPE_PROD.DATA.SWITCH_SERVICE_TEST_AND_DELETE;
-- CREATE TABLE CPE_PROD.DATA.PHARMACY_SWITCH_SERVICE_BAK CLONE CPE_PROD.DATA.PHARMACY_SWITCH_SERVICE;
-- CREATE TABLE CPE_PROD.DATA.SWITCH_SERVICE_BAK CLONE CPE_PROD.DATA.SWITCH_SERVICE;

// Truncate Source Tables
TRUNCATE TABLE CPE_PROD.DATA_DICTIONARY.RULEDATA_PHARMACY_SWITCH_SERVICE;
TRUNCATE TABLE CPE_PROD.DATA.SWITCH_SERVICE_TEST_AND_DELETE;
TRUNCATE TABLE CPE_PROD.DATA.PHARMACY_SWITCH_SERVICE;
TRUNCATE TABLE CPE_PROD.DATA.SWITCH_SERVICE;

// Suspend Tasks
ALTER TASK CPE_PROD.DATA_DICTIONARY.STREAM_TASK_RULEDATA_PHARMACY_SWITCH_SERVICE SUSPEND;
ALTER TASK CPE_PROD.DATA.STREAM_TASK_SWITCH_SERVICE_TEST_AND_DELETE SUSPEND;
ALTER TASK CPE_PROD.DATA.STREAM_TASK_PHARMACY_SWITCH_SERVICE SUSPEND;
ALTER TASK CPE_PROD.DATA.STREAM_TASK_SWITCH_SERVICE SUSPEND;

// DROP STREAMS
DROP STREAM CPE_PROD.DATA_DICTIONARY.STREAM_RULEDATA_PHARMACY_SWITCH_SERVICE;
DROP STREAM CPE_PROD.DATA.STREAM_SWITCH_SERVICE_TEST_AND_DELETE;
DROP STREAM CPE_PROD.DATA.STREAM_PHARMACY_SWITCH_SERVICE;
DROP STREAM CPE_PROD.DATA.STREAM_SWITCH_SERVICE;


// Execute Tasks
EXECUTE TASK CPE_PROD.DATA_DICTIONARY.STREAM_TASK_RULEDATA_PHARMACY_SWITCH_SERVICE;
EXECUTE TASK CPE_PROD.DATA.STREAM_TASK_SWITCH_SERVICE_TEST_AND_DELETE;
EXECUTE TASK CPE_PROD.DATA.STREAM_TASK_PHARMACY_SWITCH_SERVICE;
EXECUTE TASK CPE_PROD.DATA.STREAM_TASK_SWITCH_SERVICE;