//Execute Grants
GRANT OWNERSHIP ON TABLE CPE_PROD.DATA.PMS_MTM TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE CPE_PROD.DATA.RXDISCOUNT_CHAINSTORE_OVERRIDESNEW TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE CPE_PROD.DATA_COLLECTIONS.DC_CIM_WORK TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE CPE_PROD.DATA.RXDISCOUNT_CHAINSTORE_OVERRIDE_TYPE TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE CPE_PROD.DATA.LEGACY_SQL_DATA_COLLECTION TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE CPE_PROD.DATA.PMS_LOGIN_HISTORY TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE CPE_PROD.DATA_COLLECTIONS.DC_SCIPTPRO_WORK TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE CPE_PROD.DATA.PMS_FILL TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE CPE_PROD.DATA.CPE_CLAIM_REVERSAL_REQUESTS TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE CPE_PROD.DATA.LEGACY_MATERIALIZED_VIEW TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE CPE_PROD.DATA.LEGACY_SQL_ERRORS TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON TABLE CPE_PROD.DATA.LEGACY_SQL_CLAIM_TOTALS TO ROLE SYSADMIN COPY CURRENT GRANTS;


GRANT OWNERSHIP ON PROCEDURE CPE_PROD.DATA_COLLECTIONS.CIM_AUDIT_CONTROL(VARCHAR(16777216), NUMBER(38,0)) TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON PROCEDURE CPE_PROD.DATA_COLLECTIONS.CIM_REAL_TIME(TIMESTAMP_NTZ(9), TIMESTAMP_NTZ(9), NUMBER(38,0)) TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON PROCEDURE CPE_PROD.DATA_COLLECTIONS.DC_AUDIT(VARCHAR(16777216), VARCHAR(16777216), VARCHAR(16777216)) TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON PROCEDURE CPE_PROD.DATA_COLLECTIONS.SCRIPTPRO(TIMESTAMP_NTZ(9), TIMESTAMP_NTZ(9), NUMBER(38,0)) TO ROLE SYSADMIN COPY CURRENT GRANTS;

GRANT OWNERSHIP ON PROCEDURE CPE_PROD.DATA.CPE_CLAIM_RESPONSES_STREAM() TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON PROCEDURE CPE_DEV.DATA.CPE_CLAIM_RESPONSES_STREAM() TO ROLE SYSADMIN COPY CURRENT GRANTS;
``
-- GRANT OWNERSHIP ON STAGE 'CPE_PROD.DATA.X9ZJG470473FF1FI (Stage)' TO ROLE SYSADMIN COPY CURRENT GRANTS;     //Add Name - Ran via GUI
-- GRANT OWNERSHIP ON STAGE CPE_PROD.DATA.YR224F4OM4VDSHMR (Stage) TO ROLE SYSADMIN COPY CURRENT GRANTS;       //Add Name - Ran via GUI

GRANT OWNERSHIP ON STREAM CPE_PROD.DATA.CPE_CLAIM_REVERSAL_REQUESTS_STREAM TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON STREAM CPE_PROD.DATA.CPE_CLAIM_REVERSAL_REQUESTS_STREAM TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON STREAM CPE_PROD.DATA.STREAM_CPE_CLAIM_REVERSAL_REQUESTS TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON STREAM CPE_PROD.DATA.STREAM_PATIENT_RX_HISTORY_REQUESTS TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON STREAM CPE_PROD.DATA.STREAM_PMS_FILL TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON STREAM CPE_PROD.DATA.STREAM_PMS_LOGIN_HISTORY TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON STREAM CPE_PROD.DATA.STREAM_PMS_MTM TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON STREAM CPE_PROD.DATA.STREAM_POWERLINE_RULE_DATA_PHARMACY TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON STREAM CPE_PROD.DATA.STREAM_RXDISCOUNT_CHAINSTORE_OVERRIDESNEW TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON STREAM CPE_PROD.DATA.STREAM_RXDISCOUNT_CHAINSTORE_OVERRIDE_TYPE TO ROLE SYSADMIN COPY CURRENT GRANTS;

ALTER TASK CPE_PROD.DATA.STREAM_TASK_CPE_CLAIM_REVERSAL_REQUESTS SUSPEND;
GRANT OWNERSHIP ON TASK CPE_PROD.DATA.STREAM_TASK_CPE_CLAIM_REVERSAL_REQUESTS TO ROLE SYSADMIN COPY CURRENT GRANTS;
ALTER TASK CPE_PROD.DATA.STREAM_TASK_CPE_CLAIM_REVERSAL_REQUESTS RESUME;

ALTER TASK CPE_PROD.DATA.STREAM_TASK_PATIENT_RX_HISTORY_REQUESTS SUSPEND;
GRANT OWNERSHIP ON TASK CPE_PROD.DATA.STREAM_TASK_PATIENT_RX_HISTORY_REQUESTS TO ROLE SYSADMIN COPY CURRENT GRANTS;
ALTER TASK CPE_PROD.DATA.STREAM_TASK_PATIENT_RX_HISTORY_REQUESTS RESUME;

ALTER TASK CPE_PROD.DATA.STREAM_TASK_PMS_FILL SUSPEND;
GRANT OWNERSHIP ON TASK CPE_PROD.DATA.STREAM_TASK_PMS_FILL TO ROLE SYSADMIN COPY CURRENT GRANTS;
ALTER TASK CPE_PROD.DATA.STREAM_TASK_PMS_FILL RESUME;

ALTER TASK CPE_PROD.DATA.STREAM_TASK_PMS_LOGIN_HISTORY SUSPEND;
GRANT OWNERSHIP ON TASK CPE_PROD.DATA.STREAM_TASK_PMS_LOGIN_HISTORY TO ROLE SYSADMIN COPY CURRENT GRANTS;
ALTER TASK CPE_PROD.DATA.STREAM_TASK_PMS_LOGIN_HISTORY RESUME;

ALTER TASK CPE_PROD.DATA.STREAM_TASK_PMS_MTM SUSPEND;
GRANT OWNERSHIP ON TASK CPE_PROD.DATA.STREAM_TASK_PMS_MTM TO ROLE SYSADMIN COPY CURRENT GRANTS;
ALTER TASK CPE_PROD.DATA.STREAM_TASK_PMS_MTM RESUME;

ALTER TASK CPE_PROD.DATA.STREAM_TASK_RXDISCOUNT_CHAINSTORE_OVERRIDESNEW SUSPEND;
GRANT OWNERSHIP ON TASK CPE_PROD.DATA.STREAM_TASK_RXDISCOUNT_CHAINSTORE_OVERRIDESNEW TO ROLE SYSADMIN COPY CURRENT GRANTS;
ALTER TASK CPE_PROD.DATA.STREAM_TASK_RXDISCOUNT_CHAINSTORE_OVERRIDESNEW RESUME;

ALTER TASK CPE_PROD.DATA.STREAM_TASK_RXDISCOUNT_CHAINSTORE_OVERRIDE_TYPE SUSPEND;
GRANT OWNERSHIP ON TASK CPE_PROD.DATA.STREAM_TASK_RXDISCOUNT_CHAINSTORE_OVERRIDE_TYPE TO ROLE SYSADMIN COPY CURRENT GRANTS;
ALTER TASK CPE_PROD.DATA.STREAM_TASK_RXDISCOUNT_CHAINSTORE_OVERRIDE_TYPE RESUME;

//----------------------------------------------------------------------------------------------------------------------------------
// STATEMENT ABOVE THIS LINE HAVE BEEN RUN
//----------------------------------------------------------------------------------------------------------------------------------

GRANT OWNERSHIP ON PIPE CPE_PROD.STAGING.CPE_TRANSMISSIONS TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON PIPE CPE_PROD.STAGING.EVENTS TO ROLE SYSADMIN COPY CURRENT GRANTS;