USE DATABASE CPE_PROD;
USE SCHEMA STAGING;


DESCRIBE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_PRODGRAM;

-- TRUNCATES
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_CRITERIA_TYPE;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_CRITERIA;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_TEXT;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_VERSION;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PATIENT_NOTIFICATION;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PATIENT;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PHARMACY_NOTIFICATION;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_STATUS;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_TYPE;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_WORKFLOW;
-- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.IMAGE;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.LABEL_TYPE;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.LANGUAGE_TYPE;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.LOCATION_FILTER_TYPE;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.LOCATION_OPT_IN_CAMPAIGN;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.LOCATION_OPT_OUT_CAMPAIGN;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.LOCATION;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.NOTIFICATION_RESPONSE;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.NOTIFICATION_TYPE;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.OPT_STATUS;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.OUTCOME_TYPE;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.PATIENT_OPT_OUT_CAMPAIGN;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.PATIENT_RX_OPT_OUT_CAMPAIGN;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.PROGRAM;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.PROGRAM_OUTCOME;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.RX_VOUCHER;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.SUCCESSFUL_ALERT_TYPE;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.TABLE_LOG;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.THIRD_PARTY_TYPE;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.VENDOR_API_SETTING;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.VENDOR_PATIENT;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.VENDOR_TYPE;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.VOUCHER_STATUS;
TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.WORKFLOW_TYPE;



--Drop Streams
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_CRITERIA;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_CRITERIA_TYPE;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_NOTIFICATION_TEXT;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_NOTIFICATION_VERSION;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_PATIENT;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_PATIENT_NOTIFICATION;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_PHARMACY_NOTIFICATION;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_STATUS;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_TYPE;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_WORKFLOW;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_IMAGE;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_LABEL_TYPE;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_LANGUAGE_TYPE;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_LOCATION;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_LOCATION_FILTER_TYPE;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_LOCATION_OPT_IN_CAMPAIGN;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_LOCATION_OPT_OUT_CAMPAIGN;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_NOTIFICATION_RESPONSE;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_NOTIFICATION_TYPE;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_OPT_STATUS;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_PATIENT_OPT_OUT_CAMPAIGN;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_PATIENT_RX_OPT_OUT_CAMPAIGN;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_RX_VOUCHER;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_SUCCESSFUL_ALERT_TYPE;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_TABLE_LOG;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_THIRD_PARTY_TYPE;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_VENDOR_API_SETTING;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_VENDOR_PATIENT;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_VENDOR_TYPE;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_VOUCHER_STATUS;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_WORKFLOW_TYPE;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_NOTIFICATION_VERSION;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_WORKFLOW;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_LOCATION_OPT_IN_CAMPAIGN;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_LOCATION_OPT_OUT_CAMPAIGN;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_OUTCOME_TYPE;

--Execute Tasks
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_CRITERIA_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_CRITERIA;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_NOTIFICATION_TEXT;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_NOTIFICATION_VERSION;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_PATIENT_NOTIFICATION;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_PATIENT;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_PHARMACY_NOTIFICATION;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_STATUS;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_WORKFLOW;
-- EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK-CAMPAIGN;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_IMAGE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LABEL_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LANGUAGE_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_FILTER_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_OPT_IN_CAMPAIGN;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_OPT_OUT_CAMPAIGN;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_NOTIFICATION_RESPONSE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_NOTIFICATION_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_OPT_STATUS;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_OUTCOME_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_PATIENT_OPT_OUT_CAMPAIGN;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_PATIENT_RX_OPT_OUT_CAMPAIGN;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_PROGRAM;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_PROGRAM_OUTCOME;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_RX_VOUCHER;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_SUCCESSFUL_ALERT_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_TABLE_LOG;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_THIRD_PARTY_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VENDOR_API_SETTING;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VENDOR_PATIENT;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VENDOR_TYPE;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VOUCHER_STATUS;
EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_WORKFLOW_TYPE;



SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_CRITERIA;
SELECT COUNT(*) FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_CRITERIA;

-- SUSPEND
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_CRITERIA SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_CRITERIA_TYPE SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_NOTIFICATION_TEXT SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_NOTIFICATION_VERSION SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_PATIENT SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_PATIENT_NOTIFICATION SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_PHARMACY_NOTIFICATION SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_STATUS SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_TYPE SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_WORKFLOW SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_IMAGE SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LABEL_TYPE SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LANGUAGE_TYPE SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_FILTER_TYPE SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_OPT_IN_CAMPAIGN SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_OPT_OUT_CAMPAIGN SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_NOTIFICATION_RESPONSE SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_NOTIFICATION_TYPE SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_OPT_STATUS SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_PATIENT_OPT_OUT_CAMPAIGN SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_PATIENT_RX_OPT_OUT_CAMPAIGN SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_SUCCESSFUL_ALERT_TYPE SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_TABLE_LOG SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_THIRD_PARTY_TYPE SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VENDOR_API_SETTING SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VENDOR_PATIENT SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VENDOR_TYPE SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VOUCHER_STATUS SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_WORKFLOW_TYPE SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_NOTIFICATION_VERSION SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_WORKFLOW SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_OPT_IN_CAMPAIGN SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_OPT_OUT_CAMPAIGN SUSPEND;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_OUTCOME_TYPE SUSPEND;


-- RESUME
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_CRITERIA RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_CRITERIA_TYPE RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_NOTIFICATION_TEXT RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_NOTIFICATION_VERSION RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_PATIENT RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_PATIENT_NOTIFICATION RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_PHARMACY_NOTIFICATION RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_STATUS RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_TYPE RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_WORKFLOW RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_IMAGE RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LABEL_TYPE RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LANGUAGE_TYPE RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_FILTER_TYPE RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_OPT_IN_CAMPAIGN RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_OPT_OUT_CAMPAIGN RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_NOTIFICATION_RESPONSE RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_NOTIFICATION_TYPE RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_OPT_STATUS RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_PATIENT_OPT_OUT_CAMPAIGN RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_PATIENT_RX_OPT_OUT_CAMPAIGN RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_SUCCESSFUL_ALERT_TYPE RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_TABLE_LOG RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_THIRD_PARTY_TYPE RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VENDOR_API_SETTING RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VENDOR_PATIENT RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VENDOR_TYPE RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_VOUCHER_STATUS RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_WORKFLOW_TYPE RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_NOTIFICATION_VERSION RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_WORKFLOW RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_OPT_IN_CAMPAIGN RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION_OPT_OUT_CAMPAIGN RESUME;
ALTER TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_OUTCOME_TYPE RESUME;

DESCRIBE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_OUTCOME_TYPE;
SELECT COUNT(*) FROM  CPE_PROD.CLINICAL_PLUS.OUTCOME_TYPE;

-- [${TABLENAME};]
-- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.${TABLENAME};
-- SELECT COUNT(*) FROM  CPE_PROD.CLINICAL_PLUS.${TABLENAME};
-- SELECT COUNT(*) FROM  CPE_PROD.CLINICAL_PLUS.STREAM_${TABLENAME};
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_${TABLENAME};
-- EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_${TABLENAME}

-- [Location]
-- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.LOCATION;
-- SELECT COUNT(*) FROM  CPE_PROD.CLINICAL_PLUS.LOCATION;
-- SELECT COUNT(*) FROM  CPE_PROD.CLINICAL_PLUS.STREAM_LOCATION;
-- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_LOCATION;
-- EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_LOCATION;


-- [Criteria Type]
-- DESCRIBE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_CRITERIA_TYPE;
-- -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_CRITERIA_TYPE;
-- SELECT COUNT(*) FROM  CPE_PROD.CLINICAL_PLUS.CAMPAIGN_CRITERIA_TYPE;
-- SELECT COUNT(*) FROM  CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_CRITERIA_TYPE;
-- -- DROP STREAM CPE_PROD.CLINICAL_PLUS.STREAM_CAMPAIGN_CRITERIA_TYPE;
-- EXECUTE TASK CPE_PROD.CLINICAL_PLUS.STREAM_TASK_CAMPAIGN_CRITERIA_TYPE;

//  ^^^^ ABOVE THIS LONG COMPLETED ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// To Many To Re Sync
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.PATIENT_RX_PAYMENT_INFO;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.PATIENT_RX_PRESCRIBER_INFO;

--Re-Sync Events
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PATIENT_NOTIFICATION;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.RX_VOUCHER;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_STATUS;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.LOCATION_OPT_OUT_CAMPAIGN;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.NOTIFICATION_TYPE;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.LOCATION_FILTER_TYPE;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.LANGUAGE_TYPE;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.PROGRAM;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.PATIENT_OPT_OUT_CAMPAIGN;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.VENDOR_API_SETTING;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.LOCATION_OPT_IN_CAMPAIGN;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PATIENT;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_TEXT;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.THIRD_PARTY_TYPE;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_WORKFLOW;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.VENDOR_TYPE;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.TABLE_LOG;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.OUTCOME_TYPE;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.VENDOR_PATIENT;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PHARMACY_NOTIFICATION;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_VERSION;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.IMAGE;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.SUCCESSFUL_ALERT_TYPE;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.VOUCHER_STATUS;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.NOTIFICATION_RESPONSE;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.WORKFLOW_TYPE;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.PROGRAM_OUTCOME;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_TYPE;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN_CRITERIA_TYPE;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.OPT_STATUS;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.PATIENT_RX_OPT_OUT_CAMPAIGN;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.CAMPAIGN;
    -- TRUNCATE TABLE CPE_PROD.CLINICAL_PLUS.LABEL_TYPE;



// To Many Events To ReSync. (Maybe Update in Future)
    -- SELECT 'PATIENT_RX_PRESCRIBER_INFO' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.PATIENT_RX_PRESCRIBER_INFO
    -- UNION ALL
    -- SELECT 'PATIENT_RX_PAYMENT_INFO' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.PATIENT_RX_PAYMENT_INFO
    -- UNION ALL

// Needs to Be Updated.
    -- SELECT 'CAMPAIGN' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN

// Rows To Re-Sync
    SELECT 'CAMPAIGN_PATIENT_NOTIFICATION' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PATIENT_NOTIFICATION
    UNION ALL
    SELECT 'RX_VOUCHER' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.RX_VOUCHER
    UNION ALL
    SELECT 'CAMPAIGN_STATUS' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_STATUS
    UNION ALL
    SELECT 'LOCATION_OPT_OUT_CAMPAIGN' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.LOCATION_OPT_OUT_CAMPAIGN
    UNION ALL
    SELECT 'NOTIFICATION_TYPE' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.NOTIFICATION_TYPE
    UNION ALL
    SELECT 'LOCATION_FILTER_TYPE' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.LOCATION_FILTER_TYPE
    UNION ALL
    SELECT 'LANGUAGE_TYPE' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.LANGUAGE_TYPE
    UNION ALL
    SELECT 'LOCATION' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.LOCATION
    UNION ALL
    SELECT 'PROGRAM' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.PROGRAM
    UNION ALL
    SELECT 'PATIENT_OPT_OUT_CAMPAIGN' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.PATIENT_OPT_OUT_CAMPAIGN
    UNION ALL
    SELECT 'VENDOR_API_SETTING' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.VENDOR_API_SETTING
    UNION ALL
    SELECT 'LOCATION_OPT_IN_CAMPAIGN' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.LOCATION_OPT_IN_CAMPAIGN
    UNION ALL
    SELECT 'CAMPAIGN_PATIENT' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PATIENT
    UNION ALL
    SELECT 'CAMPAIGN_NOTIFICATION_TEXT' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_TEXT
    UNION ALL
    SELECT 'THIRD_PARTY_TYPE' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.THIRD_PARTY_TYPE
    UNION ALL
    SELECT 'CAMPAIGN_WORKFLOW' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_WORKFLOW
    UNION ALL
    SELECT 'VENDOR_TYPE' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.VENDOR_TYPE
    UNION ALL
    SELECT 'TABLE_LOG' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.TABLE_LOG
    UNION ALL
    SELECT 'OUTCOME_TYPE' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.OUTCOME_TYPE
    UNION ALL
    SELECT 'CAMPAIGN_PHARMACY_NOTIFICATION' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_PHARMACY_NOTIFICATION
    UNION ALL
    SELECT 'CAMPAIGN_NOTIFICATION_VERSION' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_NOTIFICATION_VERSION
    UNION ALL
    SELECT 'IMAGE' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.IMAGE
    UNION ALL
    SELECT 'SUCCESSFUL_ALERT_TYPE' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.SUCCESSFUL_ALERT_TYPE
    UNION ALL
    SELECT 'VOUCHER_STATUS' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.VOUCHER_STATUS
    UNION ALL
    SELECT 'NOTIFICATION_RESPONSE' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.NOTIFICATION_RESPONSE
    UNION ALL
    SELECT 'WORKFLOW_TYPE' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.WORKFLOW_TYPE
    UNION ALL
    SELECT 'PROGRAM_OUTCOME' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.PROGRAM_OUTCOME
    UNION ALL
    SELECT 'CAMPAIGN_TYPE' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_TYPE
    UNION ALL
    SELECT 'CAMPAIGN_CRITERIA_TYPE' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.CAMPAIGN_CRITERIA_TYPE
    UNION ALL
    SELECT 'OPT_STATUS' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.OPT_STATUS
    UNION ALL
    SELECT 'PATIENT_RX_OPT_OUT_CAMPAIGN' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.PATIENT_RX_OPT_OUT_CAMPAIGN
    UNION ALL
    SELECT 'VENDOR_PATIENT' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.VENDOR_PATIENT
    UNION ALL
    SELECT 'LABEL_TYPE' AS object_name, COUNT(*) AS row_count FROM CPE_PROD.CLINICAL_PLUS.LABEL_TYPE
    ORDER BY object_name ASC;

-- Old Events --
SELECT
    DATA:eventType as evetnTyype,
    COUNT(*) as eventCount
FROM CPE_PROD.STAGING.STAGE_EVENTS
WHERE INGESTED_TIMESTAMP > '2025-08-01 00:00:00.000'
  AND data:eventType in (
    // There are way to many of these events to Resync.  Skipp These.
--         'clinicalplus-patient-rx-payment-info',
--         'clinicalplus-patient-rx-prescriber-info',

    // Re-sync These
        'clinicalplus-campaign-criteria-type',
        'clinicalplus-campaign-notification-text',
        'clinicalplus-campaign-notification-version',
        'clinicalplus-campaign-patient',
        'clinicalplus-campaign-patient-notification',
        'clinicalplus-campaign-pharmacy-notification',
        'clinicalplus-campaign-status',
        'clinicalplus-campaign-workflow',
        'clinicalplus-image',
        'clinicalplus-label-type',
        'clinicalplus-language-type',
        'clinicalplus-location',
        'clinicalplus-location-filter-type',
        'clinicalplus-location-opt-in-campaign',
        'clinicalplus-location-opt-out-campaign',
        'clinicalplus-notification-response',
        'clinicalplus-notification-type',
        'clinicalplus-opt-status',
        'clinicalplus-outcome-type',
        'clinicalplus-patient-opt-out-campaign',
        'clinicalplus-patient-rx-opt-out-campaign',
        'clinicalplus-program',
        'clinicalplus-program-outcome',
        'clinicalplus-rx-voucher',
        'clinicalplus-successful-alert-type',
        'clinicalplus-table-log',
        'clinicalplus-third-party-type',
        'clinicalplus-vendor-api-setting',
        'clinicalplus-vendor-patient',
        'clinicalplus-vendor-type',
        'clinicalplus-voucher-status',
        'clinicalplus-workflow-type'
    )
GROUP BY DATA:eventType
ORDER BY DATA:eventType ASC;



SELECT
    DISTINCT DATA:eventType as eventType
FROM CPE_PROD.STAGING.STAGE_EVENTS
WHERE INGESTED_TIMESTAMP > '2025-08-01 00:00:00.000'
AND (DATA:eventType LIKE 'clinicalplus-%' OR DATA:eventType LIKE 'dataexport-clinicalplus-%')
ORDER BY DATA:eventType ASC;



-- New Events --
SELECT
    DATA:eventType as evetnTyype,
    COUNT(*) as eventCount
FROM CPE_PROD.STAGING.STAGE_EVENTS
WHERE INGESTED_TIMESTAMP > '2025-08-27 00:00:00.000'
  AND data:eventType  IN(
    'clinicalplus-campaign-criteria-type',
    'clinicalplus-campaign-notification-text',
    'clinicalplus-campaign-notification-version',
    'clinicalplus-campaign-patient-notification',
    'clinicalplus-campaign-pharmacy-notification',
    'clinicalplus-campaign-status',
    'clinicalplus-campaign-workflow',
    'clinicalplus-image',
    'clinicalplus-label-type',
    'clinicalplus-language-type',
    'clinicalplus-location',
    'clinicalplus-location-filter-type',
    'clinicalplus-location-opt-in-campaign',
    'clinicalplus-location-opt-out-campaign',
    'clinicalplus-notification-response',
    'clinicalplus-notification-type',
    'clinicalplus-opt-status',
    'clinicalplus-outcome-type',
    'clinicalplus-patient-opt-out-campaign',
    'clinicalplus-patient-rx-opt-out-campaign',
    'clinicalplus-program',
    'clinicalplus-program-outcome',
    'clinicalplus-rx-voucher',
    'clinicalplus-successful-alert-type',
    'clinicalplus-table-log',
    'clinicalplus-third-party-type',
    'clinicalplus-vendor-api-setting',
    'clinicalplus-vendor-patient',
    'clinicalplus-vendor-type',
    'clinicalplus-voucher-status',
    'clinicalplus-workflow-type'
                        )
GROUP BY DATA:eventType
ORDER BY DATA:eventType ASC;




DELETE FROM CPE_PROD.STAGING.STAGE_EVENTS
WHERE INGESTED_TIMESTAMP > '2025-08-27 00:00:00.000'
  AND data:eventType  IN(
     'clinicalplus-campaign-criteria-type',
     'clinicalplus-campaign-notification-text',
     'clinicalplus-campaign-notification-version',
     'clinicalplus-campaign-patient-notification',
     'clinicalplus-campaign-pharmacy-notification',
     'clinicalplus-campaign-status',
     'clinicalplus-campaign-workflow',
     'clinicalplus-image',
     'clinicalplus-label-type',
     'clinicalplus-language-type',
     'clinicalplus-location',
     'clinicalplus-location-filter-type',
     'clinicalplus-location-opt-in-campaign',
     'clinicalplus-location-opt-out-campaign',
     'clinicalplus-notification-response',
     'clinicalplus-notification-type',
     'clinicalplus-opt-status',
     'clinicalplus-outcome-type',
     'clinicalplus-patient-opt-out-campaign',
     'clinicalplus-patient-rx-opt-out-campaign',
     'clinicalplus-program',
     'clinicalplus-program-outcome',
     'clinicalplus-rx-voucher',
     'clinicalplus-successful-alert-type',
     'clinicalplus-table-log',
     'clinicalplus-third-party-type',
     'clinicalplus-vendor-api-setting',
     'clinicalplus-vendor-patient',
     'clinicalplus-vendor-type',
     'clinicalplus-voucher-status',
     'clinicalplus-workflow-type'
    )
;



-- New Events --
SELECT
    DATA:eventType as evetnTyype,
    COUNT(*) as eventCount
FROM CPE_PROD.STAGING.STAGE_EVENTS
WHERE INGESTED_TIMESTAMP > '2025-08-27 00:00:00.000'
  AND data:eventType  IN(
         'dataexport-clinicalplus-campaign',
         'dataexport-clinicalplus-campaign-criteria-type',
         'dataexport-clinicalplus-campaign-notification-text',
         'dataexport-clinicalplus-campaign-notification-version',
         'dataexport-clinicalplus-campaign-patient-notification',
         'dataexport-clinicalplus-campaign-pharmacy-notification',
         'dataexport-clinicalplus-campaign-status',
         'dataexport-clinicalplus-campaign-workflow',
         'dataexport-clinicalplus-image',
         'dataexport-clinicalplus-label-type',
         'dataexport-clinicalplus-language-type',
         'dataexport-clinicalplus-location',
         'dataexport-clinicalplus-location-filter-type',
         'dataexport-clinicalplus-location-opt-in-campaign',
         'dataexport-clinicalplus-location-opt-out-campaign',
         'dataexport-clinicalplus-notification-response',
         'dataexport-clinicalplus-notification-type',
         'dataexport-clinicalplus-opt-status',
         'dataexport-clinicalplus-outcome-type',
         'dataexport-clinicalplus-patient-opt-out-campaign',
         'dataexport-clinicalplus-patient-rx-opt-out-campaign',
         'dataexport-clinicalplus-program',
         'dataexport-clinicalplus-program-outcome',
         'dataexport-clinicalplus-rx-voucher',
         'dataexport-clinicalplus-successful-alert-type',
         'dataexport-clinicalplus-table-log',
         'dataexport-clinicalplus-third-party-type',
         'dataexport-clinicalplus-vendor-api-setting',
         'dataexport-clinicalplus-vendor-patient',
         'dataexport-clinicalplus-vendor-type',
         'dataexport-clinicalplus-voucher-status',
         'dataexport-clinicalplus-workflow-type'
    )
GROUP BY DATA:eventType
ORDER BY DATA:eventType ASC;
