CREATE STREAM CPE_DEV.RXMARKET.STREAM_<TABLE>
  ON TABLE CPE_DEV.STAGING.STAGE_EVENTS
  APPEND_ONLY = TRUE
  SHOW_INITIAL_ROWS = TRUE
  COMMENT = 'Stream for changes to the transactions source table';