// The following query is what the DATA SCIENCE team currently uses to monitor fill rates on key fields in the CLAIMS_COMPLETE table every day.
// The normal distribution is 70%.  Less usually indicates possible issues.

-- Fill Rate View
SELECT
    'CLAIMS_COMPLETE' AS TABLE_NAME,
    TRY_TO_DATE(DATE_OF_SERVICE, 'YYYYMMDD') AS SERVICE_DATE,
    COUNT(*) AS RECORDS_COUNT,

    ROUND((SUM(CASE WHEN RESP_PATIENT_AMOUNT_PAID IS NOT NULL THEN 1 ELSE 0 END)
            / COUNT(*) * 100), 2) AS PCT_PATIENT_PAY_POPULATED,

    ROUND((SUM(CASE WHEN RESP_INGREDIENT_COST_PAID IS NOT NULL THEN 1 ELSE 0 END)
            / COUNT(*) * 100), 2) AS PCT_INGREDIENT_COST_POPULATED,

    ROUND((SUM(CASE WHEN RESP_DISPENSING_FEE_PAID IS NOT NULL THEN 1 ELSE 0 END)
            / COUNT(*) * 100), 2) AS PCT_DISPENSING_FEE_POPULATED,

    ROUND((SUM(CASE WHEN RESP_TOTAL_AMOUNT_PAID IS NOT NULL THEN 1 ELSE 0 END)
            / COUNT(*) * 100), 2) AS PCT_TOTAL_AMOUNT_POPULATED

FROM CPE_PROD.DATA_SCIENCE_SHARE.CLAIMS_COMPLETE_VIEW
WHERE TRY_TO_DATE(DATE_OF_SERVICE, 'YYYYMMDD')
      BETWEEN CURRENT_DATE - 30
        AND CURRENT_DATE - 1
GROUP BY SERVICE_DATE
ORDER BY SERVICE_DATE DESC;