SELECT
    QUERY_ID,
    NAME,
    STATE,
    ERROR_MESSAGE,
    SCHEDULED_TIME,
    COMPLETED_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.TASK_HISTORY
WHERE SCHEDULED_TIME > '2025-01-01'
AND DATABASE_NAME = 'CPE_PROD'
AND SCHEMA_NAME = 'DATA'
AND STATE = 'FAILED'
AND NAME ILIKE 'CLAIMS_COMPLETE%'
AND ERROR_MESSAGE ILIKE '%incident%'
ORDER BY SCHEDULED_TIME DESC
;