USE DATABASE CPE_DEV;
USE SCHEMA STAGING;

SELECT *
FROM
    CPE_PROD.STAGING.STAGE_EVENTS
WHERE
    INGESTED_TIMESTAMP > CURRENT_DATE()
    AND data:eventType::VARCHAR IN (
        'transactrx-medispan-mf2ndc'
    )
    ORDER BY INGESTED_TIMESTAMP DESC
LIMIT 100;