USE DATABASE CPE_DEV;
USE SCHEMA STAGING;

SELECT *
FROM STAGING.STAGE_EVENTS
WHERE INGESTED_TIMESTAMP > '2024-09-17 00:00:00.000'
AND data:eventId in (
    // Replace with actual event IDs
    'eventid-1-placeholder',
    'eventid-2-placeholder'
);


DESCRIBE TABLE CPE_DEV.BILLING.LEGACY_PWL_CREDIT_CARDS;

SELECT
    TASK_META,
    EVENT_KEY,
    ABC,
    REQ_NABP,
    REQ_PTRK,
    REQ_BIN,
    REQ_RECEIVED_DATE_TIME,
    RES_RETURN_CODE
FROM CPE_DEV.BILLING.LEGACY_PWL_CREDIT_CARDS
ORDER BY REQ_RECEIVED_DATE_TIME
DESC;


SELECT *
FROM CPE_DEV.BILLING.CREDIT_CARDS
ORDER BY RECEIVED_DATE_TIME
DESC;

