
DESCRIBE TABLE CPE_PROD.DATA.CPE_CLAIMS_LOG;

SELECT * FROM CPE_PROD.DATA.CPE_CLAIMS_LOG LIMIT 10;

SELECT DISTINCT CPH_A3_TRANSACTION_CODE FROM CPE_PROD.DATA.CPE_CLAIMS_LOG
WHERE CPH_INGESTED_TIMESTAMP > CURRENT_DATE() -20;


SELECT DISTINCT CPH_A3_TRANSACTION_CODE
FROM CPE_PROD.DATA.CPE_CLAIMS_LOG
WHERE CPH_INGESTED_TIMESTAMP > CURRENT_DATE() -20;