-- Identify Executing Queries By Task
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'STREAM_TASK_CPE_CLAIMS_LOG',
        RESULT_LIMIT => 10
           ))
WHERE DATABASE_NAME = 'CPE_PROD'
  AND STATE = 'EXECUTING';

-- Cancel Query By Query ID
SELECT SYSTEM$CANCEL_QUERY('01c2fa91-0711-e37b-003e-2787196430ba');