USE ROLE ACCOUNTADMIN;

-- Show Failover Groups
SHOW FAILOVER GROUPS;

-- Show Databases in Failover Group
SHOW DATABASES IN FAILOVER GROUP DEVFAILOVERGROUP;
SHOW DATABASES IN FAILOVER GROUP PRODFAILOVERGROUP;

// Complete History of fail over sync attempt. NOTE:  This must be run on the account doing the replications. (The WEST)
SELECT
    REPLICATION_GROUP_NAME,
    REPLICATION_GROUP_ID,
    PHASE_NAME,
    CONVERT_TIMEZONE('America/New_York', START_TIME) AS START_TIME_EST,
    START_TIME,
    END_TIME,
    JOB_UUID,
    TOTAL_BYTES,
    OBJECT_COUNT,
    PRIMARY_SNAPSHOT_TIMESTAMP,
    ERROR

    ''
    ,'PRODFAILOVERGROUP'
FROM SNOWFLAKE.ACCOUNT_USAGE.REPLICATION_GROUP_REFRESH_HISTORY
WHERE REPLICATION_GROUP_NAME IN (
    ,'DEVFAILOVERGROUP'
)
ORDER BY START_TIME DESC
LIMIT 10;