
//====================================================================================================
// DEV
//====================================================================================================
CREATE TABLE CPE_DEV.DATA.RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS_BAK CLONE CPE_DEV.DATA.RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS;

DESCRIBE TABLE CPE_DEV.DATA.RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS_BAK;

TRUNCATE TABLE CPE_DEV.DATA.RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS;

SELECT COUNT(*) FROM CPE_DEV.DATA.RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS;
ALTER TASK CPE_DEV.DATA.STREAM_TASK_RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS SUSPEND;
DROP STREAM CPE_DEV.DATA.STREAM_RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS;
EXECUTE TASK CPE_DEV.DATA.STREAM_TASK_RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS;

//====================================================================================================
// PROD
//====================================================================================================
CREATE TABLE CPE_PROD.DATA.RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS_RESEARCH CLONE CPE_PROD.DATA.RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS;

DESCRIBE TABLE CPE_PROD.DATA.RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS_RESEARCH;

TRUNCATE TABLE CPE_PROD.DATA.RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS;

SELECT COUNT(*) FROM CPE_PROD.DATA.RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS;
SELECT COUNT(*) FROM CPE_PROD.DATA.RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS_RESEARCH;

DESCRIBE STREAM CPE_PROD.DATA.STREAM_RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS;

ALTER TASK CPE_PROD.DATA.STREAM_TASK_RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS RESUME;
DROP STREAM CPE_PROD.DATA.STREAM_RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS;

EXECUTE TASK CPE_PROD.DATA.STREAM_TASK_RULE_DATA_PHARMACY_DATA_COLLECTION_OPTIONS;