USE ROLE ACCOUNTADMIN;

USE DATABASE CPE_DEV;
-- USE DATABASE CPE_PROD;

USE WAREHOUSE COMPUTE_WH;

--GET RETENTION COUNTS FOR ALL TABLES IN DATABASE
SELECT TABLE_CATALOG AS DATABASE_NAME, TABLE_SCHEMA AS SCHEMA_NAME, TABLE_NAME AS NAME, RETENTION_TIME
FROM INFORMATION_SCHEMA.TABLES;


--GENERATE ALTER STATEMENTS FOR '90 DAY RETENTION'
SELECT 'ALTER TABLE ' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME|| ' SET DATA_RETENTION_TIME_IN_DAYS = 90;' AS RETENTION_STATEMENT
FROM INFORMATION_SCHEMA.TABLES;
