USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE CPE_DEV;
--USE DATABASE CPE_PROD;

SELECT * FROM (

    SELECT 'TABLE' AS OBJECT_TYPE, TABLE_CATALOG AS DATABASE_NAME, TABLE_SCHEMA AS SCHEMA_NAME, TABLE_NAME AS NAME, TABLE_OWNER AS OWNER FROM INFORMATION_SCHEMA.TABLES


    -- [VIEWS]
    UNION
    SELECT 'VIEW' AS OBJECT_TYPE, TABLE_CATALOG AS DATABASE_NAME, TABLE_SCHEMA AS SCHEMA_NAME, TABLE_NAME AS NAME, TABLE_OWNER AS OWNER FROM INFORMATION_SCHEMA.VIEWS


    -- [FUNCTION]
    UNION
    SELECT 'FUNCTION' AS OBJECT_TYPE, FUNCTION_CATALOG AS DATABASE_NAME, FUNCTION_SCHEMA AS SCHEMA_NAME, FUNCTION_NAME AS NAME,  FUNCTION_OWNER AS OWNER FROM INFORMATION_SCHEMA.FUNCTIONS


    -- [STAGE]
    UNION
    SELECT 'STAGE' AS OBJECT_TYPE, STAGE_CATALOG AS DATABASE_NAME, STAGE_SCHEMA AS SCHEMA_NAME, STAGE_NAME AS NAME, STAGE_OWNER AS OWNER FROM INFORMATION_SCHEMA.STAGES


    -- [PROCEDURE]
    UNION
    SELECT 'PROCEDURE' AS OBJECT_TYPE, PROCEDURE_CATALOG AS DATABASE_NAME, PROCEDURE_SCHEMA AS SCHEMA_NAME, PROCEDURE_NAME AS NAME, PROCEDURE_OWNER AS OWNER FROM INFORMATION_SCHEMA.PROCEDURES


    -- [DATABASES]
    UNION
    SELECT 'DATABASE' AS OBJECT_TYPE, DATABASE_NAME AS DATABASE_NAME, 'N/A' AS SCHEMA_NAME, DATABASE_NAME AS NAME, DATABASE_OWNER AS OWNER FROM INFORMATION_SCHEMA.DATABASES

    -- [SCHEMAS]
    UNION
    SELECT 'SCHEMA' AS OBJECT_TYPE, CATALOG_NAME AS DATABASE_NAME, SCHEMA_NAME AS SCHEMA_NAME, SCHEMA_NAME AS NAME, SCHEMA_OWNER AS OWNER FROM INFORMATION_SCHEMA.SCHEMATA

    -- [FILE FORMATS]
    UNION
    SELECT 'FILE_FORMAT' AS OBJECT_TYPE, FILE_FORMAT_CATALOG AS DATABASE_NAME, FILE_FORMAT_SCHEMA AS SCHEMA_NAME, FILE_FORMAT_NAME AS NAME, FILE_FORMAT_OWNER AS OWNER FROM INFORMATION_SCHEMA.FILE_FORMATS

    -- [PIPE]
    UNION
    SELECT 'PIPE' AS OBJECT_TYPE, PIPE_NAME AS DATABASE_NAME, PIPE_NAME AS SCHEMA_NAME, PIPE_SCHEMA AS NAME, PIPE_OWNER AS OWNER FROM INFORMATION_SCHEMA.PIPES
)
WHERE OWNER = 'ACCOUNTADMIN' AND DATABASE_NAME = CURRENT_DATABASE();






-- ========================
-- [DATABASE LEVEL INFO - Not Available in Informational Schema]
-- ========================

//STEP1 - Choose DB Context.
USE DATABASE CPE_PROD;

//STEP2 - Choose Schema
USE SCHEMA DATA;                    //AT the time the only SCHEMA wtih Streamts is DATA.
-- USE SCHEMA DATA_COLLECTIONS;
-- USE SCHEMA BILLING;
-- USE SCHEMA MPI;
-- USE SCHEMA PUBLIC;
-- USE SCHEMA STAGING;

//STEP3 - Choos Account Level Object (Thosse objects that' arent available in the informational schemea.)
-- SHOW TASKS;     //TASKS
-- SET OBJ_TYPE = 'STREAM'; SHOW STREAMS;
SET OBJ_TYPE = 'TASK'; SHOW TASKS;



//STEP4 - Filter Those Account Level Objects By Owner
SELECT
    $OBJ_TYPE AS OBJECT_TYPE,
    rs."database_name" AS DATABASE_NAME,
    rs."schema_name" AS SCHEMA_NAME,
    rs."name" AS NAME,
    rs."owner" AS OWNER
FROM TABLE (RESULT_SCAN(LAST_QUERY_ID())) as rs
WHERE OWNER = 'ACCOUNTADMIN';








-- ========================
-- [ACCOUNT LEVEL INFO]
-- ========================

//STEP1 - Choose Account Level Object
SET OBJ_TYPE = 'USER'; SHOW USERS;
-- SET OBJ_TYPE = 'ROLE'; SHOW ROLES;
-- SET OBJ_TYPE = 'WAREHOUSE'; SHOW WAREHOUSES;
-- SET OBJ_TYPE = 'SHARE'; SHOW SHARES;

//STEP2 - Execute Query
SELECT
    $OBJ_TYPE AS OBJECT_TYPE,
    rs."name" AS NAME,
    rs."owner" AS OWNER
FROM TABLE (RESULT_SCAN(LAST_QUERY_ID())) as rs
WHERE OWNER = 'ACCOUNTADMIN' OR OWNER = 'SYSADMIN';



/**
[DONT USE CURRENLTY]
**/
-- [SEQUENCES]

--[MASKING POLICIES]
-- SHOW MASKING POLICIES; //Looks like we have no masking policies in any environement.

--[ROW ACCESS POLICIES]
-- SHOW ROW ACCESS POLICIES; //Looks like we have no row access policies in any environement.

--[TAGS]
-- SHOW TAGS; //Looks like we have no tags in any environement.

-- [RESOURCE MONITORS]
-- SHOW RESOURCE MONITORS;  //Looks like we have no resource moniotrs in any environement.