SHOW INTEGRATIONS;
DESCRIBE INTEGRATION SNS_NOTIFICATION;

-- Trigger a notification
CALL SYSTEM$SEND_SNOWFLAKE_NOTIFICATION(
    SNOWFLAKE.NOTIFICATION.TEXT_PLAIN('This is a test message'),
    SNOWFLAKE.NOTIFICATION.INTEGRATION('SNS_NOTIFICATION')
);

-- Verify Integration
SELECT *
FROM TABLE(CPE_DEV.INFORMATION_SCHEMA.NOTIFICATION_HISTORY(
    START_TIME => DATEADD('hour', -1, CURRENT_TIMESTAMP()),
    END_TIME => CURRENT_TIMESTAMP(),
    INTEGRATION_NAME => 'SNS_NOTIFICATION'
));

-- Test With Task
DESCRIBE TASK CPE_DEV.DATA.FAILING_TASK;
ALTER TASK CPE_DEV.DATA.FAILING_TASK SET ERROR_INTEGRATION = SNS_NOTIFICATION;
EXECUTE TASK CPE_DEV.DATA.FAILING_TASK;

--- Show Tasks that have integrations.
SHOW TASKS ->> SELECT "database_name", "schema_name", "name", "error_integration"
FROM $1
WHERE ARRAY_SIZE("predecessors") = 0
AND "database_name" = 'CPE_PROD'
AND "schema_name" <> 'DB_CACHE'
AND "error_integration" <> 'SNS_NOTIFICATION'
;